version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

